name: Build and deploy Hugo website

on: 
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push pages
      run: ./publish.sh
